/*
Overseerr API

Testing MoviesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package overseerr_go

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_overseerr_go_MoviesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MoviesAPIService MovieMovieIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var movieId float32

		resp, httpRes, err := apiClient.MoviesAPI.MovieMovieIdGet(context.Background(), movieId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MoviesAPIService MovieMovieIdRatingsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var movieId float32

		resp, httpRes, err := apiClient.MoviesAPI.MovieMovieIdRatingsGet(context.Background(), movieId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MoviesAPIService MovieMovieIdRatingscombinedGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var movieId float32

		resp, httpRes, err := apiClient.MoviesAPI.MovieMovieIdRatingscombinedGet(context.Background(), movieId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MoviesAPIService MovieMovieIdRecommendationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var movieId float32

		resp, httpRes, err := apiClient.MoviesAPI.MovieMovieIdRecommendationsGet(context.Background(), movieId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MoviesAPIService MovieMovieIdSimilarGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var movieId float32

		resp, httpRes, err := apiClient.MoviesAPI.MovieMovieIdSimilarGet(context.Background(), movieId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
