/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr_go

import (
	"encoding/json"
)

// checks if the AuthLogoutPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLogoutPost200Response{}

// AuthLogoutPost200Response struct for AuthLogoutPost200Response
type AuthLogoutPost200Response struct {
	Status *string `json:"status,omitempty"`
}

// NewAuthLogoutPost200Response instantiates a new AuthLogoutPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLogoutPost200Response() *AuthLogoutPost200Response {
	this := AuthLogoutPost200Response{}
	return &this
}

// NewAuthLogoutPost200ResponseWithDefaults instantiates a new AuthLogoutPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLogoutPost200ResponseWithDefaults() *AuthLogoutPost200Response {
	this := AuthLogoutPost200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AuthLogoutPost200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthLogoutPost200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AuthLogoutPost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AuthLogoutPost200Response) SetStatus(v string) {
	o.Status = &v
}

func (o AuthLogoutPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLogoutPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableAuthLogoutPost200Response struct {
	value *AuthLogoutPost200Response
	isSet bool
}

func (v NullableAuthLogoutPost200Response) Get() *AuthLogoutPost200Response {
	return v.value
}

func (v *NullableAuthLogoutPost200Response) Set(val *AuthLogoutPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLogoutPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLogoutPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLogoutPost200Response(val *AuthLogoutPost200Response) *NullableAuthLogoutPost200Response {
	return &NullableAuthLogoutPost200Response{value: val, isSet: true}
}

func (v NullableAuthLogoutPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLogoutPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


