/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr_go

import (
	"encoding/json"
)

// checks if the SettingsAboutGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsAboutGet200Response{}

// SettingsAboutGet200Response struct for SettingsAboutGet200Response
type SettingsAboutGet200Response struct {
	Version *string `json:"version,omitempty"`
	TotalRequests *float32 `json:"totalRequests,omitempty"`
	TotalMediaItems *float32 `json:"totalMediaItems,omitempty"`
	Tz NullableString `json:"tz,omitempty"`
	AppDataPath *string `json:"appDataPath,omitempty"`
}

// NewSettingsAboutGet200Response instantiates a new SettingsAboutGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsAboutGet200Response() *SettingsAboutGet200Response {
	this := SettingsAboutGet200Response{}
	return &this
}

// NewSettingsAboutGet200ResponseWithDefaults instantiates a new SettingsAboutGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsAboutGet200ResponseWithDefaults() *SettingsAboutGet200Response {
	this := SettingsAboutGet200Response{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SettingsAboutGet200Response) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsAboutGet200Response) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SettingsAboutGet200Response) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SettingsAboutGet200Response) SetVersion(v string) {
	o.Version = &v
}

// GetTotalRequests returns the TotalRequests field value if set, zero value otherwise.
func (o *SettingsAboutGet200Response) GetTotalRequests() float32 {
	if o == nil || IsNil(o.TotalRequests) {
		var ret float32
		return ret
	}
	return *o.TotalRequests
}

// GetTotalRequestsOk returns a tuple with the TotalRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsAboutGet200Response) GetTotalRequestsOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalRequests) {
		return nil, false
	}
	return o.TotalRequests, true
}

// HasTotalRequests returns a boolean if a field has been set.
func (o *SettingsAboutGet200Response) HasTotalRequests() bool {
	if o != nil && !IsNil(o.TotalRequests) {
		return true
	}

	return false
}

// SetTotalRequests gets a reference to the given float32 and assigns it to the TotalRequests field.
func (o *SettingsAboutGet200Response) SetTotalRequests(v float32) {
	o.TotalRequests = &v
}

// GetTotalMediaItems returns the TotalMediaItems field value if set, zero value otherwise.
func (o *SettingsAboutGet200Response) GetTotalMediaItems() float32 {
	if o == nil || IsNil(o.TotalMediaItems) {
		var ret float32
		return ret
	}
	return *o.TotalMediaItems
}

// GetTotalMediaItemsOk returns a tuple with the TotalMediaItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsAboutGet200Response) GetTotalMediaItemsOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalMediaItems) {
		return nil, false
	}
	return o.TotalMediaItems, true
}

// HasTotalMediaItems returns a boolean if a field has been set.
func (o *SettingsAboutGet200Response) HasTotalMediaItems() bool {
	if o != nil && !IsNil(o.TotalMediaItems) {
		return true
	}

	return false
}

// SetTotalMediaItems gets a reference to the given float32 and assigns it to the TotalMediaItems field.
func (o *SettingsAboutGet200Response) SetTotalMediaItems(v float32) {
	o.TotalMediaItems = &v
}

// GetTz returns the Tz field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SettingsAboutGet200Response) GetTz() string {
	if o == nil || IsNil(o.Tz.Get()) {
		var ret string
		return ret
	}
	return *o.Tz.Get()
}

// GetTzOk returns a tuple with the Tz field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsAboutGet200Response) GetTzOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tz.Get(), o.Tz.IsSet()
}

// HasTz returns a boolean if a field has been set.
func (o *SettingsAboutGet200Response) HasTz() bool {
	if o != nil && o.Tz.IsSet() {
		return true
	}

	return false
}

// SetTz gets a reference to the given NullableString and assigns it to the Tz field.
func (o *SettingsAboutGet200Response) SetTz(v string) {
	o.Tz.Set(&v)
}
// SetTzNil sets the value for Tz to be an explicit nil
func (o *SettingsAboutGet200Response) SetTzNil() {
	o.Tz.Set(nil)
}

// UnsetTz ensures that no value is present for Tz, not even an explicit nil
func (o *SettingsAboutGet200Response) UnsetTz() {
	o.Tz.Unset()
}

// GetAppDataPath returns the AppDataPath field value if set, zero value otherwise.
func (o *SettingsAboutGet200Response) GetAppDataPath() string {
	if o == nil || IsNil(o.AppDataPath) {
		var ret string
		return ret
	}
	return *o.AppDataPath
}

// GetAppDataPathOk returns a tuple with the AppDataPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsAboutGet200Response) GetAppDataPathOk() (*string, bool) {
	if o == nil || IsNil(o.AppDataPath) {
		return nil, false
	}
	return o.AppDataPath, true
}

// HasAppDataPath returns a boolean if a field has been set.
func (o *SettingsAboutGet200Response) HasAppDataPath() bool {
	if o != nil && !IsNil(o.AppDataPath) {
		return true
	}

	return false
}

// SetAppDataPath gets a reference to the given string and assigns it to the AppDataPath field.
func (o *SettingsAboutGet200Response) SetAppDataPath(v string) {
	o.AppDataPath = &v
}

func (o SettingsAboutGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsAboutGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.TotalRequests) {
		toSerialize["totalRequests"] = o.TotalRequests
	}
	if !IsNil(o.TotalMediaItems) {
		toSerialize["totalMediaItems"] = o.TotalMediaItems
	}
	if o.Tz.IsSet() {
		toSerialize["tz"] = o.Tz.Get()
	}
	if !IsNil(o.AppDataPath) {
		toSerialize["appDataPath"] = o.AppDataPath
	}
	return toSerialize, nil
}

type NullableSettingsAboutGet200Response struct {
	value *SettingsAboutGet200Response
	isSet bool
}

func (v NullableSettingsAboutGet200Response) Get() *SettingsAboutGet200Response {
	return v.value
}

func (v *NullableSettingsAboutGet200Response) Set(val *SettingsAboutGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsAboutGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsAboutGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsAboutGet200Response(val *SettingsAboutGet200Response) *NullableSettingsAboutGet200Response {
	return &NullableSettingsAboutGet200Response{value: val, isSet: true}
}

func (v NullableSettingsAboutGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsAboutGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


