/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr_go

import (
	"encoding/json"
)

// checks if the GenresTvGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenresTvGet200ResponseInner{}

// GenresTvGet200ResponseInner struct for GenresTvGet200ResponseInner
type GenresTvGet200ResponseInner struct {
	Id *float32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewGenresTvGet200ResponseInner instantiates a new GenresTvGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenresTvGet200ResponseInner() *GenresTvGet200ResponseInner {
	this := GenresTvGet200ResponseInner{}
	return &this
}

// NewGenresTvGet200ResponseInnerWithDefaults instantiates a new GenresTvGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenresTvGet200ResponseInnerWithDefaults() *GenresTvGet200ResponseInner {
	this := GenresTvGet200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GenresTvGet200ResponseInner) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenresTvGet200ResponseInner) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GenresTvGet200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GenresTvGet200ResponseInner) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GenresTvGet200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenresTvGet200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GenresTvGet200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GenresTvGet200ResponseInner) SetName(v string) {
	o.Name = &v
}

func (o GenresTvGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenresTvGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGenresTvGet200ResponseInner struct {
	value *GenresTvGet200ResponseInner
	isSet bool
}

func (v NullableGenresTvGet200ResponseInner) Get() *GenresTvGet200ResponseInner {
	return v.value
}

func (v *NullableGenresTvGet200ResponseInner) Set(val *GenresTvGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGenresTvGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGenresTvGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenresTvGet200ResponseInner(val *GenresTvGet200ResponseInner) *NullableGenresTvGet200ResponseInner {
	return &NullableGenresTvGet200ResponseInner{value: val, isSet: true}
}

func (v NullableGenresTvGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenresTvGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


