/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr_go

import (
	"encoding/json"
)

// checks if the UserUserIdRequestsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserUserIdRequestsGet200Response{}

// UserUserIdRequestsGet200Response struct for UserUserIdRequestsGet200Response
type UserUserIdRequestsGet200Response struct {
	PageInfo *PageInfo `json:"pageInfo,omitempty"`
	Results []MediaRequest `json:"results,omitempty"`
}

// NewUserUserIdRequestsGet200Response instantiates a new UserUserIdRequestsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserUserIdRequestsGet200Response() *UserUserIdRequestsGet200Response {
	this := UserUserIdRequestsGet200Response{}
	return &this
}

// NewUserUserIdRequestsGet200ResponseWithDefaults instantiates a new UserUserIdRequestsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserUserIdRequestsGet200ResponseWithDefaults() *UserUserIdRequestsGet200Response {
	this := UserUserIdRequestsGet200Response{}
	return &this
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *UserUserIdRequestsGet200Response) GetPageInfo() PageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret PageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdRequestsGet200Response) GetPageInfoOk() (*PageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *UserUserIdRequestsGet200Response) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PageInfo and assigns it to the PageInfo field.
func (o *UserUserIdRequestsGet200Response) SetPageInfo(v PageInfo) {
	o.PageInfo = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *UserUserIdRequestsGet200Response) GetResults() []MediaRequest {
	if o == nil || IsNil(o.Results) {
		var ret []MediaRequest
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdRequestsGet200Response) GetResultsOk() ([]MediaRequest, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *UserUserIdRequestsGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []MediaRequest and assigns it to the Results field.
func (o *UserUserIdRequestsGet200Response) SetResults(v []MediaRequest) {
	o.Results = v
}

func (o UserUserIdRequestsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserUserIdRequestsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableUserUserIdRequestsGet200Response struct {
	value *UserUserIdRequestsGet200Response
	isSet bool
}

func (v NullableUserUserIdRequestsGet200Response) Get() *UserUserIdRequestsGet200Response {
	return v.value
}

func (v *NullableUserUserIdRequestsGet200Response) Set(val *UserUserIdRequestsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUserIdRequestsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUserIdRequestsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUserIdRequestsGet200Response(val *UserUserIdRequestsGet200Response) *NullableUserUserIdRequestsGet200Response {
	return &NullableUserUserIdRequestsGet200Response{value: val, isSet: true}
}

func (v NullableUserUserIdRequestsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUserIdRequestsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


