/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr_go

import (
	"encoding/json"
)

// checks if the SettingsJobsJobIdSchedulePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsJobsJobIdSchedulePostRequest{}

// SettingsJobsJobIdSchedulePostRequest struct for SettingsJobsJobIdSchedulePostRequest
type SettingsJobsJobIdSchedulePostRequest struct {
	Schedule *string `json:"schedule,omitempty"`
}

// NewSettingsJobsJobIdSchedulePostRequest instantiates a new SettingsJobsJobIdSchedulePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsJobsJobIdSchedulePostRequest() *SettingsJobsJobIdSchedulePostRequest {
	this := SettingsJobsJobIdSchedulePostRequest{}
	return &this
}

// NewSettingsJobsJobIdSchedulePostRequestWithDefaults instantiates a new SettingsJobsJobIdSchedulePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsJobsJobIdSchedulePostRequestWithDefaults() *SettingsJobsJobIdSchedulePostRequest {
	this := SettingsJobsJobIdSchedulePostRequest{}
	return &this
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *SettingsJobsJobIdSchedulePostRequest) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJobsJobIdSchedulePostRequest) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *SettingsJobsJobIdSchedulePostRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *SettingsJobsJobIdSchedulePostRequest) SetSchedule(v string) {
	o.Schedule = &v
}

func (o SettingsJobsJobIdSchedulePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsJobsJobIdSchedulePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	return toSerialize, nil
}

type NullableSettingsJobsJobIdSchedulePostRequest struct {
	value *SettingsJobsJobIdSchedulePostRequest
	isSet bool
}

func (v NullableSettingsJobsJobIdSchedulePostRequest) Get() *SettingsJobsJobIdSchedulePostRequest {
	return v.value
}

func (v *NullableSettingsJobsJobIdSchedulePostRequest) Set(val *SettingsJobsJobIdSchedulePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsJobsJobIdSchedulePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsJobsJobIdSchedulePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsJobsJobIdSchedulePostRequest(val *SettingsJobsJobIdSchedulePostRequest) *NullableSettingsJobsJobIdSchedulePostRequest {
	return &NullableSettingsJobsJobIdSchedulePostRequest{value: val, isSet: true}
}

func (v NullableSettingsJobsJobIdSchedulePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsJobsJobIdSchedulePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


