name: Go

on: [push]

env:
  GO_DIR: ./overseerr

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          working-directory: ${{ env.GO_DIR }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
        working-directory: ${{ env.GO_DIR }}
      - name: Install dependencies
        run: go get
        working-directory: ${{ env.GO_DIR }}
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
        working-directory: ${{ env.GO_DIR }}
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
          working-directory: ${{ env.GO_DIR }}
